// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigEdit } from "./ConfigEdit";

export type ConfigBatchWriteParams = { filePath: string, edits: Array<ConfigEdit>, expectedVersion: string | null, };
